Repository boostcamp-2020/IssueTracker-28, pull requests merged in 2020-11, with the labels that each got.

#28 Github Login JWT token 방식으로 변경 & FE Auth 기능 구현
  client/package-lock.json
  client/src/App.jsx
  client/src/components/user/UserLogin/index.js
  client/src/util/cookie.js
  client/src/util/getToken.js
  client/src/util/localStorage.js
  server/app.js
  server/package-lock.json
  server/package.json
  server/passport/jwt.js
  server/routes/auth/controller.js
  server/routes/auth/index.js
Labels: 👾 frontend, 📡 backend, 🛠 fix

#35 Issue Context API 적용
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.jsx
  client/src/api/issue.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/index.js
  client/src/components/issues/index.js
  client/src/contexts/IssuesContext.js
  client/src/contexts/asyncActionUtils.js
  client/src/pages/IssuePage.js
  client/src/pages/UserPage.js
  client/webpack.config.js
  server/app.js
  server/package-lock.json
Labels: 🌵 contextAPI, 👾 frontend

#36 Milestone 조회 API 구현
  README.md
  client/src/App.js
  client/src/App.jsx
  client/src/api/milestone.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/milestones/index.js
  client/src/contexts/IssuesContext.js
  client/src/contexts/milestonesContext.js
  client/src/pages/IssuePage.js
  client/src/pages/MilestonePage.js
  server/models/milestone.js
  server/routes/milestone/controller.js
  server/routes/milestone/index.js
  server/services/db/milestone.js
  server/services/milestone.js
Labels: 🌵 contextAPI, 👾 frontend, 📡 backend

#37 Label Context 생성 및 전체 라벨 목록 조회 API 구현
  client/src/App.js
  client/src/api/label.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/label/index.js
  client/src/components/user/UserLogin/index.js
  client/src/contexts/IssuesContext.js
  client/src/contexts/LabelContext.js
  client/src/pages/IssuePage.js
  client/src/pages/NewIssuePage.js
  client/webpack.config.js
  server/routes/label/controller.js
  server/routes/label/index.js
  server/services/db/label.js
  server/services/label.js
Labels: 🌵 contextAPI, 👾 frontend, 📡 backend

#38 user, users context API 구현 & 인증 로직 부분 수정
  client/src/App.js
  client/src/api/common.js
  client/src/api/issue.js
  client/src/api/user.js
  client/src/components/issues/IssueHeader/Filters.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/user/UserLogin/index.js
  client/src/components/user/index.js
  client/src/contexts/UserContext.js
  client/src/contexts/UsersContext.js
  client/src/pages/UserPage.js
  client/src/util/cookie.js
  client/src/util/localStorage.js
  client/src/utils/cookie.js
  client/src/utils/getToken.js
  server/app.js
  server/config/config.js
  server/models/index.js
  server/passport/jwt.js
  server/passport/passport.js
  server/routes/auth/controller.js
  server/routes/auth/index.js
  server/routes/index.js
  server/services/db/user.js
  server/services/user.js
Labels: 🌵 contextAPI, 🛠 fix

#39 IssueContext + 필터 & issueFilter함수 구현 및 SearchBar Filter 테스트 & 필터 초기화 기능
  client/src/components/issues/IssueHeader/SearchBar.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/issues/IssueHeader/style.js
  client/src/components/issues/IssueList/List/index.js
  client/src/contexts/IssuesContext.js
  client/src/util/cookie.js
  client/src/util/filterIssue.js
Labels: 🌵 contextAPI, 👾 frontend

#49 검색,팝업필터 기능 & 체크박스 기능 구현 & Mark as 컴포넌트 & 초기화 및 보여줄 이슈목록이 없는 경우 처리
  client/package-lock.json
  client/src/api/issue.js
  client/src/components/issues/IssueHeader/Filters.js
  client/src/components/issues/IssueHeader/SearchBar.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/issues/IssueHeader/style.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/List/style.js
  client/src/components/issues/IssueList/List/testItems.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/IssueList/ListHeader/style.js
  client/src/components/issues/IssueList/index.js
  client/src/components/milestone/index.js
  client/src/contexts/IssuesContext.js
  client/src/contexts/milestonesContext.js
  client/src/pages/MilestonePage.js
  client/src/utils/filterIssue.js
  client/src/utils/getFilterMessage.js
  client/webpack.config.js
  server/routes/index.js
Labels: 👾 frontend

#51 새로운 이슈 생성 페이지의 팝업 이벤트 구현
  client/src/App.js
  client/src/components/assignees/index.js
  client/src/components/assignees/style.js
  client/src/components/header/header.js
  client/src/components/header/index.js
  client/src/components/header/style.js
  client/src/components/input/index.js
  client/src/components/input/style.js
  client/src/components/issues/style.js
  client/src/components/labels/index.js
  client/src/components/labels/style.js
  client/src/components/milestone/index.js
  client/src/components/milestone/style.js
  client/src/contexts/milestonesContext.js
  client/src/pages/IssuePage.js
  client/src/pages/NewIssuePage.js
Labels: 🎨 style, 👾 frontend

#52 New Issue Page Event 및 API 기능 구현
  client/src/App.js
  client/src/components/input/index.js
  client/src/components/input/style.js
  client/src/components/issues/IssueHeader/Buttons/NewIssueButton.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/milestones/index.js
  client/src/pages/NewIssuePage.js
  client/src/pages/TestPage.js
  client/webpack.config.js
  server/routes/issue/controller.js
  server/services/db/issue.js
  server/services/issue.js
Labels: 🎨 style, 👾 frontend, 📡 backend

#53 체크박스 props -> ContextAPI 방식으로 변경 & constants분리 및 코드 정리
  client/public/images/logoImage.png
  client/public/images/spinner.gif
  client/public/images/spinner2.gif
  client/public/images/spinner3.gif
  client/public/images/spinner4.gif
  client/src/components/issues/IssueHeader/Filters.js
  client/src/components/issues/IssueHeader/SearchBar.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/issues/IssueHeader/style.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/IssueList/ListHeader/style.js
  client/src/components/issues/IssueList/index.js
  client/src/components/user/UserLogin/index.js
  client/src/components/user/UserLogin/style.js
  client/src/constants/actionTypes.js
  client/src/constants/filtersItems.js
  client/src/contexts/CheckedItemContext.js
  client/src/pages/IssuePage.js
  client/webpack.config.js
Labels: 🎨 style, 👾 frontend, 🛠 fix

#54 이슈 목록 페이지 기능 추가
  client/src/App.js
  client/src/components/issues/IssueHeader/Filters.js
  client/src/components/issues/IssueHeader/SearchBar.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/List/style.js
  client/src/components/issues/IssueList/List/testItems.js
  client/src/components/issues/IssueList/ListHeader/handler.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/IssueList/ListHeader/style.js
  client/src/components/issues/IssueList/index.js
  client/src/contexts/IssuesContext.js
  client/src/contexts/LabelContext.js
  client/src/contexts/UsersContext.js
  client/src/pages/MilestonePage.js
  client/src/utils/filterIssue.js
  client/src/utils/getFilterMessage.js
Labels: 🎨 style, 👾 frontend

#57 라벨, 마일스톤 API 구현 및 Sidebar props 데이터 수정
  client/src/components/input/index.js
  client/src/pages/NewIssuePage.js
  server/routes/label/controller.js
  server/routes/label/index.js
  server/routes/milestone/controller.js
  server/routes/milestone/index.js
  server/services/db/label.js
  server/services/db/milestone.js
  server/services/label.js
  server/services/milestone.js
Labels: 📡 backend

#58 Issue Detail Layout 구현
  client/src/App.js
  client/src/components/IssueDetail/Content/MainContent/Comment/index.js
  client/src/components/IssueDetail/Content/MainContent/Comment/style.js
  client/src/components/IssueDetail/Content/MainContent/index.js
  client/src/components/IssueDetail/Content/MainContent/style.js
  client/src/components/IssueDetail/Content/index.js
  client/src/components/IssueDetail/index.js
  client/src/components/input/InputForm/buttonWrapper.js
  client/src/components/input/InputForm/index.js
  client/src/components/input/InputForm/style.js
  client/src/components/input/index.js
  client/src/components/input/style.js
  client/src/components/issues/IssueHeader/Buttons/MilestonesButton.js
Labels: 🎨 style, 👾 frontend, 🧥 refactor

#59 이슈 상세 조회 API 구현 및 상세 페이지 header 구현
  client/package-lock.json
  client/package.json
  client/src/api/issue.js
  client/src/components/IssueDetail/Header/index.js
  client/src/components/IssueDetail/Header/style.js
  client/src/components/IssueDetail/index.js
  client/src/components/IssueDetail/style.js
  client/src/components/header/index.js
  client/src/components/header/style.js
  client/src/components/issues/IssueHeader/Buttons/style.js
  server/models/comment.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/services/db/issue.js
  server/services/issue.js
Labels: 🎨 style, 👾 frontend, 📡 backend

#60 Mark as 기능 API 구현 및 새로운 이슈 생성 페이지 CSS
  README.md
  client/src/api/issue.js
  client/src/components/input/style.js
  client/src/components/issues/IssueHeader/Buttons/MilestonesButton.js
  client/src/components/issues/IssueHeader/Buttons/style.js
  client/src/components/issues/IssueHeader/Filters.js
  client/src/components/issues/IssueHeader/SearchBar.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/List/style.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/contexts/IssuesContext.js
  client/src/index.css
  client/src/index.js
  client/src/utils/uncheckAllFilters.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/services/db/issue.js
  server/services/issue.js
Labels: 🎨 style, 👾 frontend, 📡 backend

#61 Milestone 페이지 ui 구현
  client/src/components/milestones/Header/index.js
  client/src/components/milestones/Header/style.js
  client/src/components/milestones/List/Milestone/index.js
  client/src/components/milestones/List/Milestone/style.js
  client/src/components/milestones/List/index.js
  client/src/components/milestones/List/style.js
  client/src/components/milestones/index.js
  client/src/components/milestones/style.js
Labels: 🎨 style, 👾 frontend

#78 라벨 목록 페이지 - api연동, 이벤트 적용 / 유저 이미지 css & 경과시간 함수 구현
  client/public/images/empty-user.png
  client/src/api/label.js
  client/src/components/IssueDetail/Content/MainContent/Comment/index.js
  client/src/components/IssueDetail/Content/MainContent/Comment/style.js
  client/src/components/IssueDetail/Header/index.js
  client/src/components/Sidebar/assignees/index.js
  client/src/components/Sidebar/assignees/style.js
  client/src/components/Sidebar/labels/style.js
  client/src/components/input/form/style.js
  client/src/components/input/index.js
  client/src/components/input/style.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/IssueList/ListHeader/style.js
  client/src/components/labels/Header/index.js
  client/src/components/labels/List/Label/index.js
  client/src/components/labels/List/Label/style.js
  client/src/components/labels/List/index.js
  client/src/components/labels/List/style.js
  client/src/components/labels/NewLabel/index.js
  client/src/components/labels/NewLabel/style.js
  client/src/components/labels/index.js
  client/src/contexts/LabelContext.js
  client/src/utils/getElapsedTime.js
  client/webpack.config.js
  server/models/label.js
  server/routes/auth/controller.js
  server/routes/label/controller.js
  server/routes/label/index.js
Labels: 🎨 style, 👾 frontend, 📡 backend

#79 이슈 상세 페이지 - sidebar 추가 & 헤더 기능 구현
  .eslintrc.json
  client/src/App.js
  client/src/api/auth.js
  client/src/api/http.js
  client/src/api/issue.js
  client/src/api/label.js
  client/src/api/milestone.js
  client/src/api/user.js
  client/src/components/IssueDetail/Content/MainContent/Comment/style.js
  client/src/components/IssueDetail/Content/MainContent/index.js
  client/src/components/IssueDetail/Content/MainContent/style.js
  client/src/components/IssueDetail/Content/index.js
  client/src/components/IssueDetail/Header/index.js
  client/src/components/IssueDetail/Header/style.js
  client/src/components/IssueDetail/index.js
  client/src/components/Sidebar/assignees/index.js
  client/src/components/Sidebar/index.js
  client/src/components/Sidebar/labels/index.js
  client/src/components/Sidebar/labels/style.js
  client/src/components/Sidebar/milestone/index.js
  client/src/components/input/form/buttonWrapper.js
  client/src/components/issueDetail/content/style.js
  client/src/components/issues/IssueHeader/Buttons/FiltersButton.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/IssueList/index.js
  client/src/components/issues/header/Filters.js
  client/src/components/issues/header/SearchBar.js
  client/src/components/issues/header/buttons/FiltersButton.js
  client/src/components/issues/header/buttons/LabelsButton.js
  client/src/components/issues/header/buttons/MilestonesButton.js
  client/src/components/issues/header/buttons/NewIssueButton.js
  client/src/components/issues/header/buttons/index.js
  client/src/components/issues/header/buttons/style.js
  client/src/components/issues/header/index.js
  client/src/components/issues/header/style.js
  client/src/components/issues/index.js
  client/src/pages/NewIssuePage.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/services/db/issue.js
  server/services/issue.js
Labels: 🎨 style, 👾 frontend, 📡 backend, 🛠 fix

#80 이슈 상세 페이지 - 이벤트 및 API 연동
  client/src/components/IssueDetail/Content/MainContent/Comment/index.js
  client/src/components/IssueDetail/Content/MainContent/Comment/style.js
  client/src/components/IssueDetail/Content/MainContent/index.js
  client/src/components/IssueDetail/Content/MainContent/style.js
  client/src/components/IssueDetail/Header/style.js
  client/src/components/IssueDetail/index.js
  client/src/components/Sidebar/labels/index.js
  client/src/components/input/form/index.js
  client/src/components/input/form/style.js
  client/src/components/input/index.js
  client/src/components/input/style.js
  server/routes/comment/controller.js
  server/routes/comment/index.js
  server/routes/index.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/services/comment.js
  server/services/db/comment.js
  server/services/db/issue.js
  server/services/issue.js
Labels: 🎨 style, 👾 frontend, 📡 backend

#81 마일스톤 page 이벤트 등록, 새로운 마일스톤 생성 페이지 ui 구현
  client/src/App.js
  client/src/components/Sidebar/milestone/index.js
  client/src/components/milestones/Header/index.js
  client/src/components/milestones/List/Milestone/index.js
  client/src/components/milestones/List/index.js
  client/src/components/milestones/List/style.js
  client/src/components/milestones/index.js
  client/src/components/newMilestone/index.js
  client/src/components/newMilestone/input/index.js
  client/src/components/newMilestone/input/style.js
  client/src/components/newMilestone/style.js
  client/src/pages/NewMilestonePage.js
  client/src/utils/date.js
  server/routes/label/controller.js
  server/routes/label/index.js
  server/routes/milestone/controller.js
  server/routes/milestone/index.js
  server/services/db/label.js
  server/services/db/milestone.js
Labels: 🎨 style, 👾 frontend, 📡 backend, 🛠 fix

#87 검색 구현 & sidebar 관련 API 구현
  client/src/App.js
  client/src/components/IssueDetail/Content/index.js
  client/src/components/Sidebar/assignees/index.js
  client/src/components/Sidebar/index.js
  client/src/components/Sidebar/labels/style.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/header/SearchBar.js
  client/src/components/issues/header/index.js
  client/src/contexts/IssuesContext.js
  client/src/utils/getFilterMessage.js
  server/models/label.js
  server/models/user.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/services/db/issue.js
  server/services/db/milestone.js
  server/services/issue.js
Labels: 👾 frontend, 📡 backend

#88 이슈 상세 페이지 Context API 적용, Preview 구현
  client/src/api/comment.js
  client/src/api/issue.js
  client/src/api/upload.js
  client/src/components/IssueDetail/Content/MainContent/Comment/index.js
  client/src/components/IssueDetail/Content/MainContent/Comment/style.js
  client/src/components/IssueDetail/Content/MainContent/index.js
  client/src/components/IssueDetail/Content/MainContent/style.js
  client/src/components/IssueDetail/Header/index.js
  client/src/components/IssueDetail/Header/style.js
  client/src/components/IssueDetail/index.js
  client/src/components/input/form/index.js
  client/src/components/input/form/style.js
  client/src/components/input/index.js
  client/src/components/input/preview.js
  client/src/components/input/style.js
  client/src/components/issueDetail/content/style.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/header/buttons/style.js
  client/src/contexts/IssueDetailContext.js
  client/src/contexts/IssuesContext.js
  client/src/contexts/MilestonesContext.js
  client/src/pages/IssueDetailPage.js
  client/src/utils/getElapsedTime.js
  client/src/utils/uncheckAllFilters.js
  server/routes/auth/controller.js
  server/routes/comment/controller.js
  server/routes/comment/index.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/routes/upload/index.js
Labels: 🌵 contextAPI, 👾 frontend, 📡 backend, 🧥 refactor

#89 이슈 목록 페이지 assigned 필터 반영 & 유저 이미지 적용 & 시간,필터 버그 수정
  .prettierrc
  client/src/api/label.js
  client/src/components/Sidebar/assignees/index.js
  client/src/components/Sidebar/labels/style.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/IssueList/ListHeader/style.js
  client/src/components/labels/List/Label/index.js
  client/src/components/labels/NewLabel/style.js
  client/src/constants/filtersItems.js
  client/src/contexts/LabelContext.js
  client/src/utils/colorHandler.js
  client/src/utils/filterIssue.js
  client/src/utils/getElapsedTime.js
  client/src/utils/uncheckAllFilters.js
  server/passport/passport.js
  server/routes/label/controller.js
  server/services/db/label.js
  server/services/db/user.js
  server/services/issue.js
  server/services/user.js
Labels: 👾 frontend, 📡 backend, 🛠 fix

#92 [Fix] 오류 해결
  client/src/App.js
  client/src/components/input/index.js
  client/src/components/issueDetail/content/index.js
  client/src/components/issueDetail/content/main/comment/index.js
  client/src/components/issueDetail/content/main/index.js
  client/src/components/issueDetail/header/index.js
  client/src/components/issues/header/buttons/NewIssueButton.js
  client/src/components/issues/header/index.js
  client/src/pages/IssueDetailPage.js
Labels: 🛠 fix

#94 mentioning filter 적용, 마일스톤 페이지 리팩토링
  client/src/api/milestone.js
  client/src/components/editMilestone/index.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/milestones/List/index.js
  client/src/constants/filtersItems.js
  client/src/constants/status.js
  client/src/contexts/IssuesContext.js
  client/src/utils/filterIssue.js
  client/src/utils/getFilterMessage.js
  server/services/db/issue.js
  server/services/issue.js
Labels: 👾 frontend, 🛠 fix, 🧥 refactor

#95 Sidebar 기능 구현 완료
  .eslintrc.json
  client/src/api/issue.js
  client/src/components/Sidebar/assignees/index.js
  client/src/components/Sidebar/assignees/style.js
  client/src/components/Sidebar/index.js
  client/src/components/Sidebar/labels/index.js
  client/src/components/Sidebar/labels/style.js
  client/src/components/Sidebar/milestone/index.js
  client/src/components/Sidebar/milestone/style.js
  client/src/components/input/index.js
  client/src/components/issueDetail/content/index.js
  client/src/components/issueDetail/header/index.js
  client/src/components/issueDetail/index.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/ListHeader/style.js
  client/src/components/newMilestone/index.js
  client/src/components/newMilestone/input/index.js
  client/src/components/user/UserLogin/index.js
  client/src/contexts/IssueDetailContext.js
  client/src/contexts/LabelContext.js
  client/src/contexts/MilestonesContext.js
  client/src/contexts/UserContext.js
  client/src/contexts/UsersContext.js
  client/src/pages/NewIssuePage.js
  client/src/utils/cookie.js
  server/passport/passport.js
  server/routes/auth/controller.js
  server/routes/issue/controller.js
  server/services/issue.js
  server/services/milestone.js
Labels: 🌵 contextAPI, 🎨 style, 👾 frontend, 📡 backend, 🛠 fix

#96 Issue, Comment 삭제
  client/src/api/comment.js
  client/src/api/issue.js
  client/src/components/input/form/index.js
  client/src/components/input/form/style.js
  client/src/components/input/index.js
  client/src/components/issueDetail/content/main/comment/index.js
  client/src/components/issueDetail/content/main/index.js
  client/src/components/issueDetail/content/style.js
  client/src/components/issueDetail/index.js
  client/src/components/issues/IssueList/List/Issue/index.js
  server/routes/comment/controller.js
  server/routes/comment/index.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/services/comment.js
  server/services/db/comment.js
  server/services/db/issue.js
  server/services/issue.js
Labels: 👾 frontend, 📡 backend

#97 Label, Issue 관련 버그 수정
  client/public/images/small-load-spinner.gif
  client/src/api/label.js
  client/src/components/Sidebar/assignees/index.js
  client/src/components/Sidebar/labels/index.js
  client/src/components/input/form/style.js
  client/src/components/issueDetail/content/main/comment/style.js
  client/src/components/issueDetail/content/main/index.js
  client/src/components/issueDetail/content/main/style.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/labels/Header/index.js
  client/src/components/labels/List/Label/index.js
  client/src/components/labels/NewLabel/index.js
  client/src/index.css
  server/routes/user/controller.js
  server/routes/user/index.js
  server/services/user.js
Labels: 👾 frontend, 🛠 fix

#99 클라이언트 서버 인증 로직 추가
  client/public/images/404Image.png
  client/public/images/blackCat.ico
  client/public/images/favicon.ico
  client/public/images/rainbowCat.ico
  client/public/images/whitecat.ico
  client/public/index.html
  client/src/App.js
  client/src/api/label.js
  client/src/api/milestone.js
  client/src/api/user.js
  client/src/components/header/index.js
  client/src/components/header/style.js
  client/src/components/input/index.js
  client/src/components/issueDetail/content/main/comment/index.js
  client/src/components/issueDetail/content/main/index.js
  client/src/components/issueDetail/index.js
  client/src/components/issues/IssueList/List/style.js
  client/src/components/issues/header/SearchBar.js
  client/src/components/labels/List/index.js
  client/src/components/milestones/List/index.js
  client/src/components/user/UserLogin/index.js
  client/src/components/user/UserLogin/style.js
  client/src/pages/ErrorPage.js
  server/routes/index.js
Labels: 👾 frontend, 📡 backend

#100 [Refactor] milestone 관련 수정 및 express-validator 추가
  client/package-lock.json
  client/package.json
  client/src/api/milestone.js
  client/src/components/input/form/index.js
  client/src/components/input/index.js
  client/src/components/labels/Header/index.js
  client/src/components/milestones/List/Milestone/index.js
  client/src/components/milestones/List/index.js
  client/src/components/newMilestone/index.js
  client/src/utils/filterIssue.js
  server/middlewares/validator.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/routes/label/controller.js
  server/routes/label/index.js
  server/routes/milestone/controller.js
  server/routes/milestone/index.js
  server/services/db/issue.js
  server/services/db/milestone.js
  server/services/milestone.js
Labels: 🧥 refactor

#102 Labels 버그 해결
  client/src/components/labels/index.js
  client/src/components/labels/list/index.js
  client/src/components/labels/list/label/index.js
  client/src/components/labels/newLabel/index.js
  client/src/components/milestones/list/index.js
Labels: 🛠 fix
