Repository boostcamp-2020/IssueTracker-28, pull requests merged in 2020-10, with the labels that each got.

#17 week1 day2 이슈 목록 컴포넌트 구현(IssueHeader)
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/issues/Issue.jsx
  client/src/components/issues/IssueHeader.jsx
  client/src/components/issues/IssueHeader/Buttons/FiltersButton.js
  client/src/components/issues/IssueHeader/Buttons/LabelsButton.js
  client/src/components/issues/IssueHeader/Buttons/MilestonesButton.js
  client/src/components/issues/IssueHeader/Buttons/NewIssueButton.js
  client/src/components/issues/IssueHeader/Buttons/index.js
  client/src/components/issues/IssueHeader/Buttons/style.js
  client/src/components/issues/IssueHeader/SearchBar.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/issues/IssueHeader/style.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/List/style.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/IssueList/ListHeader/style.js
  client/src/components/issues/IssueList/index.js
  client/src/components/issues/IssueList/style.js
  client/src/components/issues/index.js
  client/src/pages/IssuePage.jsx
  package-lock.json
  package.json
Labels: frontend

#16 week1-day2 이슈 목록 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/IssueList/List/index.js
  client/src/components/issues/IssueList/ListHeader/index.js
  client/src/components/issues/IssueList/ListHeader/style.js
  client/src/components/issues/IssueList/index.js
  client/src/components/issues/IssueList/style.js
  client/src/components/issues/index.js
  client/src/pages/IssuePage.jsx
  client/webpack.config.js
  package.json
Labels: frontend

#15 DB 연동 및 테이블 생성
  server/app.js
  server/bin/www
  server/config/config.js
  server/models/comment.js
  server/models/index.js
  server/models/issue-assignee.js
  server/models/issue-label.js
  server/models/issue.js
  server/models/label.js
  server/models/milestone.js
  server/models/user.js
  server/package-lock.json
  server/package.json
Labels: backend

#18 week1-day2 Github 소셜로그인 연동
  server/app.js
  server/package-lock.json
  server/package.json
  server/passport/jwt.js
  server/passport/passport.js
  server/routes/auth/controller.js
  server/routes/auth/index.js
  server/routes/index.js
Labels: backend

#22 전체 이슈 목록 조회 API 구현
  .eslintrc.json
  .prettierrc
  client/package.json
  client/src/App.jsx
  client/src/components/issues/IssueHeader/Buttons/FiltersButton.js
  client/src/components/issues/IssueHeader/Buttons/style.js
  client/src/components/issues/IssueHeader/SearchBar.js
  client/src/components/issues/IssueList/List/Issue/index.js
  client/src/components/issues/IssueList/List/Issue/style.js
  client/src/components/issues/IssueList/List/style.js
  client/src/components/issues/IssueList/index.js
  client/src/components/issues/index.js
  client/src/index.js
  client/src/pages/IssuePage.jsx
  client/src/pages/UserPage.jsx
  server/app.js
  server/package.json
  server/passport/jwt.js
  server/passport/passport.js
  server/routes/auth/controller.js
  server/routes/auth/index.js
  server/routes/index.js
  server/routes/issue/controller.js
  server/routes/issue/index.js
  server/services/db/issue.js
  server/services/issue.js
Labels: backend

#24 전체 이슈 목록 조회 API 응답 데이터 수정
  client/webpack.config.js
  server/app.js
  server/config/config.js
  server/routes/auth/index.js
  server/routes/index.js
  server/services/db/issue.js
  server/services/issue.js
Labels: backend

#23 더미데이터를 이용한 검색 기능 구현
  client/src/components/issues/IssueHeader/Filters.js
  client/src/components/issues/IssueHeader/SearchBar.js
  client/src/components/issues/IssueHeader/index.js
  client/src/components/issues/IssueHeader/style.js
Labels: frontend

#27 클라이언트의 oAuth 인증요청 처리 / userPage(첫 화면) 컴포넌트 구현
  client/package-lock.json
  client/public/images/issuelogo.png
  client/public/index.html
  client/src/App.jsx
  client/src/api/auth.js
  client/src/api/http.js
  client/src/components/user/UserLogin/index.js
  client/src/components/user/UserLogin/style.js
  client/src/components/user/index.js
  client/src/components/user/style.js
  client/src/index.js
  client/src/pages/UserPage.jsx
  client/src/util/getToken.js
  client/webpack.config.js
  server/app.js
  server/package-lock.json
  server/package.json
  server/passport/passport.js
  server/routes/auth/controller.js
  server/routes/auth/index.js
  server/routes/index.js
Labels: backend, frontend
